spring.application.name=bikes

# Configuração de locale
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bikes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate

# Exibe SQL no log
spring.jpa.show-sql=true

# Formata o SQL no log
spring.jpa.properties.hibernate.format_sql=false

# Cria/atualiza as tabelas a partir das entidades
spring.jpa.hibernate.ddl-auto=update