spring.application.name=bikes
# LOCALE config
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# MYSQL Config
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bikes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=root



# JPA
# exibe sql no log
spring.jpa.show-sql=true 
# exibe em uma única linha
spring.jpa.properties.hibernate.format_sql=false
# cria as tabelas a partir das classes entidades
spring.jpa.hibernate.ddl-auto=update